version: "3.8"

services:
  wald:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
    environment:
      - PATH="/opt/venv/bin:$PATH"
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ROCKSDB_PRIMARY_PATH=/data/command
      - ROCKSDB_STATE_PATH=/data/state
      - ROCKSDB_WALSEQ_STATE_KEY=wal_seq_start
      - REDIS_QUEUE_NAME=saga_queue
  redis:
    image: redis
    ports:
      - "6379:6379"
